### PR TITLE
make study participant field only visible if the user is in the study

### PR DESCRIPTION
**Pull request by Hlamallama**

### CODE REVIEW

**Comment by fritzbrand** [comment]
@Hlamallama can we maybe change that "study_optin" variable to be a little more descriptive of the study we are talking about, something like "baseline_optin"?

**Review by KaitCrawford — COMMENTED** [review]
@Hlamallama this looks good. Just one thing: pls add a test for if the user's study_optin field is False 🙏 that way we've got both scenario's tested

**Comment by KaitCrawford** [comment]
> @Hlamallama can we maybe change that "study_optin" variable to be a little more descriptive of the study we are talking about, something like "baseline_optin"?

**Comment by KaitCrawford** [comment]
> @Hlamallama can we maybe change that "study_optin" variable to be a little more descriptive of the study we are talking about, something like "baseline_optin"?

@fritzbrand I'm happy with it being more descriptive, but I don't know what works. Just want to caution against `baseline_optin` though since the study is more than the baseline assessment, so I don't think it's accurate.

**Comment by fritzbrand** [comment]
@KaitCrawford yea you are right, lets leave it as is for now, so I am +1

**Review by KaitCrawford — APPROVED** [review]
👍 looks great!!

**Pull request merged**
